# Server
server.port=8080

# ─── PostgreSQL Database ───
spring.datasource.url=jdbc:postgresql://localhost:5432/indentdb
spring.datasource.username=postgres
spring.datasource.password=Manish@0108
spring.datasource.driver-class-name=org.postgresql.Driver

# ─── JPA / Hibernate ───
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ─── MinIO ───
minio.url=http://localhost:9000
minio.access-key=admin
minio.secret-key=password123
minio.bucket-name=indent-documents

# ─── File Upload ───
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB